- name: nancurunir
  hosts: all
  become: yes


  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
      

    - name: set the root password
      user:
        name: root
        password: "{{root_hash}}"
        state: present
        create_home: yes
    
    - name: create unprivileged user
      user:
        name: "{{user_name}}"
        password: "{{user_hash}}"
        state: present
        create_home: yes
      

    - name: selinux permissive
      shell: setenforce 0
      ignore_errors: yes


    - name: selinux disable on reboot
      shell: "sed -i 's /enforce/disabled/g' /etc/selinux/config/ /etc/selinux/config"

    
     - name: reboot the box to disable selinux
        reboot:


    - name: drop the root flag
      copy:
        dest: "/root/root-flag.txt"
        content: |
          "{{root_flag}}"
        owner: root
        group: root


    - name: drop the user flag
      copy:
        dest: "/home/{{user_name}}/user-flag.txt"
        content: |
          "{{user_flag}}"
        owner: "{{user_name}}"
        group: "{{user_name}}"


    - name: remove welcome page
      file:
        path: "/etc/httpd/conf.d/welcome.conf"
        state: absent


    - name: upload index
      copy:
        src: "files/index.html"
        dest: "/var/www/html/index.html"
        owner: root
        group: root
        mode: 644


    - name: Start service httpd, if not running
      service:
        name: httpd
        state: started
        enabled: yes