- name: nancurunir
  hosts: all
  become: yes


  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
      

    - name: set the root password
      user:
        name: root
        password: "{{root_hash}}"
        state: present
        create_home: yes
    
    - name: create unprivileged user
      user:
        name: "{{user_name}}"
        password: "{{user_hash}}"
        state: present
        create_home: yes
      

    - name: selinux permissive
      shell: setenforce 0
      ignore_errors: yes


    - name: selinux disable on reboot
      shell: "sed -i 's /enforce/disabled/g' /etc/selinux/config/ /etc/selinux/config"

    - name: drop the root flag
      copy:
        dest: "/root/root-flag.txt"
        content: |
          "{{root_flag}}"
        owner: root
        group: root


    - name: drop the user flag
      copy:
        dest: "/home/{{user_name}}/user-flag.txt"
        content: |
          "{{user_flag}}"
        owner: "{{user_name}}"
        group: "{{user_name}}"

    - name: upload index
      copy:
        src: "files/index.html"
        dest: "/var/www/html/index.html"
        owner: www-data
        group: www-data
        mode: 644

    - name: copy phpMyAdmin directory
      copy:
        src: "files/phpMyAdmin-4.8.1-english"
        dest: "/usr/share/phpmyadmin"
        owner: www-data
        group: www-data
        mode: 755

    - name: copy phpMyAdmin config file
      copy:
        src: "files/phpmyadmin.conf"
        dest: "/etc/apache2/conf-available/phpmyadmin.conf"

    - name: copy php.ini file
      copy:
        src: "files/php.ini"
        dest: "/etc/php/7.4/apache2/php.ini"

    - name: reboot the box to disable selinux
      reboot: