- name: trollshaws
  hosts: all
  become: yes
  vars_prompt:
  - name: deployer_pass
    prompt: what is the deployer's password for mysql?
    private: yes
  - name: teemipsqlpass
    prompt: what do you want teemipuser's mysql password to be?
    private: yes

  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
      
    - name: set the root password
      user:
        name: root
        password: "{{root_hash}}"
        state: present
        create_home: yes
    
    - name: create user
      user:
        name: "{{user_name}}"
        password: "{{user_hash}}"
        groups: wheel
        state: present
        create_home: yes
      
    - name: drop the root flag
      copy:
        dest: "/root/root-flag.txt"
        content: |
          "{{root_flag}}"
        owner: root
        group: root

    - name: drop the user flag
      copy:
        dest: "/home/{{user_name}}/user-flag.txt"
        content: |
          "{{user_flag}}"
        owner: "{{user_name}}"
        group: "{{user_name}}"

    - name: start http service
      shell: sudo service httpd start

    - name: start mysql service
      shell: sudo service mysqld start

    - name: enable http service
      shell: sudo chkconfig httpd on

    - name: enable mysql service
      shell: sudo chkconfig mysqld on

    - name: making teemip directory
      shell: sudo mkdir /var/www/html/teemip

    - name: unarchive teemip files
      unarchive:
        src: "files/TeemIp-2.3.1-1811.zip"
        dest: "/var/www/html/teemip/"

    - name: change owner of /teemip/web directory
      shell: chown -R apache:apache /var/www/html/teemip/web

    - name: create teemip mysql user
      mysql_query:
        login_user: deployer
        login_password: "{{deployer_pass}}"
        query: 
        - CREATE DATABASE teemipdb;
        - CREATE USER 'teemipuser'@'localhost' IDENTIFIED BY '{{teemipsqlpass}}';
        - GRANT ALL ON teemipdb.* TO 'teemipuser'@'localhost';
        - ALTER USER 'teemipuser'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{teemipsqlpass}}';
        - DROP USER 'deployer'@'localhost';
        - FLUSH PRIVILEGES;

    - name: remove old mysql server config file
      shell: sudo rm -f /etc/my.cnf.d/mysql-server.cnf

    - name: upload new mysql server config file
      copy:
        src: "files/mysql-server.cnf"
        dest: "/etc/my.cnf.d/mysql-server.cnf"

    - name: Allow http through local firewall
      shell: sudo firewall-cmd --permanent --add-service=http

    - name: Reload Firewall
      shell: sudo firewall-cmd --reload

    - name: remove old selinux config file
      shell: sudo rm -f /etc/selinux/config

    - name: copy new selinux config file
      copy: 
        src: "files/config"
        dest: "/etc/selinux/config"

    - name: reboot the box to change hostname
      reboot:
